package main

import "fmt"

// Runner: calls per-topic demo functions organized in separate files.
func main() {
	fmt.Println("Intermediate topics runner — calling demos 57–102")
	Demo57Closures()
	Demo58Recursion()
	Demo59Pointers()
	Demo60StringsRunes()
	Demo61FmtVerbs()
	Demo62FmtPackage()
	Demo63Structs()
	Demo64Methods()
	Demo65Interfaces()
	Demo66StructEmbedding()
	Demo67Generics()
	Demo68Errors()
	Demo69CustomErrors()
	Demo70StringFunctions()
	Demo71StringFormatting()
	Demo72TextTemplates()
	Demo73Regex()
	Demo74Time()
	Demo75Epoch()
	Demo76TimeFormatParse()
	Demo77Random()
	Demo78NumberParsing()
	Demo79URLParsing()
	Demo80Bufio()
	Demo81Base64()
	Demo82SHA()
	Demo83WriteFile()
	Demo84ReadFile()
	Demo85LineFilters()
	Demo86FilePaths()
	Demo87Directories()
	Demo88TempFilesDirs()
	Demo89EmbedDirective()
	Demo90CmdArgsFlags()
	Demo91SubCommands()
	Demo92EnvVars()
	Demo93Logging()
	Demo94JSON()
	Demo95StructTags()
	Demo96XML()
	Demo97GoExtensionNotes()
	Demo98TypeConversions()
	Demo99IO()
	Demo100Math()
	Demo101MathExamples()
	Demo102Summary()
}
